const block = (...lines: string[]): string => lines.join('\n');

export interface SourceControlMutation {
  id: string;
  control: string;
  target: string;
  intendedCase: `A6-T-${string}`;
  search: string;
  replacement: string;
}

export const SOURCE_CONTROL_MUTATIONS: readonly SourceControlMutation[] = [
  {
    id: 'A6-M-01-FOUNDER-COMPANY-OWNERSHIP',
    control: 'founder/company ownership check',
    target: 'test/aico-006-spike/postgres-decision-unit-of-work.ts',
    intendedCase: 'A6-T-REPLAY-REVOKED-01',
    search: block(
      '    if (',
      '      company === undefined ||',
      '      company.current_founder_id !== founder.id ||',
      "      company.status !== 'ACTIVE'",
      '    ) {',
      "      throw new Gate01ProofError('AUTHORITY_FORBIDDEN', 403);",
      '    }',
    ),
    replacement: block(
      '    // MUTANT: founder/company ownership and active-company checks removed.',
      '    if (company === undefined) {',
      "      throw new Gate01ProofError('AUTHORITY_FORBIDDEN', 403);",
      '    }',
    ),
  },
  {
    id: 'A6-M-02-EXACT-ARTIFACT-VERSION',
    control: 'exact Artifact Version/current-pointer check',
    target: 'test/aico-006-spike/gate01-command.service.ts',
    intendedCase: 'A6-T-STALE-ARTIFACT-01',
    search: block(
      '      state.artifact_id === expected.artifact_id &&',
      '      state.artifact_version_id === expected.artifact_version_id &&',
      '      state.artifact_version === expected.artifact_version &&',
      '      state.artifact_checksum === expected.artifact_checksum &&',
    ),
    replacement: block(
      '      // MUTANT: exact artifact identity/version/checksum comparison removed.',
      '      true &&',
    ),
  },
  {
    id: 'A6-M-03-EXPECTED-RUN-LOCK',
    control: 'expected run state/row-version lock',
    target: 'test/aico-006-spike/gate01-command.service.ts',
    intendedCase: 'A6-T-STALE-RUN-01',
    search: block(
      '      state.state === expected.run_state &&',
      '      state.stage === expected.run_stage &&',
      '      state.run_row_version === expected.run_row_version &&',
    ),
    replacement: block(
      '      // MUTANT: locked Run state/stage/row-version comparison removed.',
      '      true &&',
    ),
  },
  {
    id: 'A6-M-04-BEHAVIOR-VERSION-BINDING',
    control: 'policy/workflow/employee version binding',
    target: 'test/aico-006-spike/deterministic-policy-decision.service.ts',
    intendedCase: 'A6-T-STALE-POLICY-01',
    search: '    const reason = this.denialReason(input);',
    replacement: block(
      '    // MUTANT: an unsupported policy version bypasses all policy denial rules.',
      "    const reason = input.policy.semantic_version === 'unsupported/v9'",
      '      ? null',
      '      : this.denialReason(input);',
    ),
  },
  {
    id: 'A6-M-05-ACTION-TIME-BINDING',
    control: 'parameter, budget, environment, and expiry binding',
    target: 'test/aico-006-spike/gate01-command.service.ts',
    intendedCase: 'A6-T-MISSING-PARAMETER-01',
    search: block(
      '    if (',
      "      policyDecision.effect === 'ALLOW' &&",
      '      !this.matchesCompleteAllowBinding(policyDecision, policyInput, context.requestDigest)',
      '    ) {',
      '      policyDecision = this.invalidAllowDenial(policyDecision, state);',
      '    }',
    ),
    replacement: block(
      '    // MUTANT: a changed parameter digest bypasses the complete ALLOW binding check.',
      '    if (',
      "      policyDecision.effect === 'ALLOW' &&",
      '      policyDecision.binding.parameters_digest === context.requestDigest &&',
      '      !this.matchesCompleteAllowBinding(policyDecision, policyInput, context.requestDigest)',
      '    ) {',
      '      policyDecision = this.invalidAllowDenial(policyDecision, state);',
      '    }',
    ),
  },
  {
    id: 'A6-M-06-IDEMPOTENCY-DIGEST',
    control: 'idempotency request-digest comparison',
    target: 'test/aico-006-spike/postgres-decision-unit-of-work.ts',
    intendedCase: 'A6-T-KEY-COLLISION-01',
    search: block(
      '    if (receipt.request_digest !== scope.requestDigest) {',
      "      throw new Gate01ProofError('IDEMPOTENCY_CONFLICT', 409);",
      '    }',
    ),
    replacement: block(
      '    // MUTANT: changed business digest is treated as a replay.',
      '    if (false && receipt.request_digest !== scope.requestDigest) {',
      "      throw new Gate01ProofError('IDEMPOTENCY_CONFLICT', 409);",
      '    }',
    ),
  },
  {
    id: 'A6-M-07-DECISION-EVENT-ATOMICITY',
    control: 'decision plus canonical policy.decided/approval.decided event/outbox atomicity',
    target: 'test/aico-006-spike/gate01-command.service.ts',
    intendedCase: 'A6-T-APPROVE-01',
    search: block(
      '    await context.runner.query(',
      '      `INSERT INTO outbox_messages (',
      '        id, company_id, event_id, topic, envelope, envelope_digest, created_at',
      '      ) VALUES ($1,$2,$3,$4,$5::jsonb,$6,$7)`,',
      '      [',
      '        newId(),',
      '        context.authority.companyId,',
      '        eventId,',
      '        eventType,',
      '        JSON.stringify(envelope),',
      '        canonicalDigest(envelope),',
      '        occurredAt,',
      '      ],',
      '    );',
    ),
    replacement: block(
      '    // MUTANT: domain event commits without its transactional outbox row.',
      '    void envelope;',
    ),
  },
  {
    id: 'A6-M-08-CONTINUATION-AUTHORITY',
    control: 'continuation uniqueness and source-decision validation',
    target: 'test/aico-006-spike/proof-schema.ts',
    intendedCase: 'A6-T-SERVICE-BYPASS-01',
    search: block(
      '  UNIQUE (company_id, run_id, logical_key),',
      '  FOREIGN KEY (company_id, run_id) REFERENCES runs(company_id, id),',
      '  FOREIGN KEY (company_id, decision_record_id)',
      '    REFERENCES founder_gate_decisions(company_id, id),',
      '  FOREIGN KEY (company_id, policy_decision_id)',
      '    REFERENCES policy_decisions(company_id, id),',
    ),
    replacement: block(
      '  -- MUTANT: continuation logical uniqueness and decision/policy authority removed.',
      '  FOREIGN KEY (company_id, run_id) REFERENCES runs(company_id, id),',
    ),
  },
  {
    id: 'A6-M-09-TERMINAL-CANCELED-REVALIDATION',
    control: 'terminal/canceled-state revalidation',
    target: 'test/aico-006-spike/gate01-command.service.ts',
    intendedCase: 'A6-T-TERMINAL-01',
    search: '    const state = await this.lockGate01State(context, request);',
    replacement: block(
      '    const state = await this.lockGate01State(context, request);',
      "    if (['CANCELED', 'FAILED', 'COMPLETED'].includes(state.state)) {",
      '      // MUTANT: reopen terminal state before policy and mutation revalidation.',
      '      await context.runner.query(',
      "        `UPDATE runs SET state='AWAITING_BRIEF_APPROVAL', stage='PRODUCT'",
      '         WHERE company_id=$1 AND id=$2`,',
      '        [context.authority.companyId, state.run_id],',
      '      );',
      "      state.state = 'AWAITING_BRIEF_APPROVAL';",
      "      state.stage = 'PRODUCT';",
      '    }',
    ),
  },
  {
    id: 'A6-M-10-AUTHORITY-BEFORE-REPLAY',
    control: 'current authentication/Founder/Company authority before receipt replay',
    target: 'test/aico-006-spike/postgres-decision-unit-of-work.ts',
    intendedCase: 'A6-T-REPLAY-REVOKED-01',
    search: block(
      '      const authority = await this.lockCurrentAuthority(runner, authorityInput);',
      "      await this.onFailpoint('AFTER_AUTHORITY_LOCK');",
    ),
    replacement: block(
      '      // MUTANT: disclose a stored receipt before current authority is checked.',
      '      const unsafeReplayRows = (await runner.query(',
      '        `SELECT request_digest, response_status, response_body',
      '         FROM command_receipts',
      "         WHERE company_id=$1 AND operation='DECIDE_GATE_01' AND idempotency_key=$2`,",
      '        [authorityInput.companyId, receiptScope.idempotencyKey],',
      '      )) as ReceiptRow[];',
      '      const unsafeReplay = unsafeReplayRows[0];',
      '      if (unsafeReplay !== undefined) {',
      '        await runner.commitTransaction();',
      '        return {',
      '          status: unsafeReplay.response_status,',
      '          body: this.asReplay<T>(unsafeReplay.response_body),',
      '          replayed: true,',
      '        };',
      '      }',
      '      const authority = await this.lockCurrentAuthority(runner, authorityInput);',
      "      await this.onFailpoint('AFTER_AUTHORITY_LOCK');",
    ),
  },
  {
    id: 'A6-M-11-TAGGED-REDACTED-DENY',
    control: 'tagged redacted DENY with no victim identifiers and maximum_uses=0',
    target: 'test/aico-006-spike/gate01-command.service.ts',
    intendedCase: 'A6-T-DENIAL-EVENT-01',
    search: block(
      '            supplied_reference_digest: canonicalDigest({',
      '              company_id: context.authority.companyId,',
      '              supplied_reference: input.suppliedReference,',
      '            }),',
    ),
    replacement: block(
      '            supplied_reference_digest: canonicalDigest({',
      '              company_id: context.authority.companyId,',
      '              supplied_reference: input.suppliedReference,',
      '            }),',
      '            // MUTANT: redacted DENY retains a victim Run identifier.',
      '            run_id: input.request.command.run_id,',
    ),
  },
  {
    id: 'A6-M-12-DENIAL-EVIDENCE',
    control: 'SRS-FR-087 denial decision/policy.decided preservation',
    target: 'test/aico-006-spike/gate01-command.service.ts',
    intendedCase: 'A6-T-DENIAL-EVENT-01',
    search:
      '        const eventId = await this.appendCompanyPolicyEvent(context, input.request, decision);',
    replacement: block(
      '        // MUTANT: denial persists without its policy.decided/outbox evidence.',
      '        const eventId = newId();',
    ),
  },
  {
    id: 'A6-M-13-ZERO-ADAPTER-CALL',
    control: 'adapter-call zero-effect assertion',
    target: 'test/aico-006-spike/gate01-command.service.ts',
    intendedCase: 'A6-T-DENIAL-EVENT-01',
    search:
      '        const eventId = await this.appendCompanyPolicyEvent(context, input.request, decision);',
    replacement: block(
      '        const eventId = await this.appendCompanyPolicyEvent(context, input.request, decision);',
      '        // MUTANT: a denied company-scoped action reaches an external adapter.',
      '        await context.runner.query(',
      '          `INSERT INTO adapter_effect_ledger',
      '            (id, company_id, run_id, effect_kind, effect_key)',
      "           VALUES ($1,$2,$3,'EXTERNAL',$4)`,",
      '          [',
      '            newId(),',
      '            context.authority.companyId,',
      '            input.request.command.run_id,',
      '            decision.policy_decision_id,',
      '          ],',
      '        );',
    ),
  },
  {
    id: 'A6-M-14-CANARY-SCAN',
    control: 'evidence redaction/canary scan',
    target: 'test/aico-006-spike/gate01-command.service.ts',
    intendedCase: 'A6-T-AUDIT-REDACTION-01',
    search: "    await context.failpoint('AFTER_FOUNDER_DECISION');",
    replacement: block(
      "    await context.failpoint('AFTER_FOUNDER_DECISION');",
      '    // MUTANT: a protected canary leaks into a retained adapter evidence row.',
      "    if (request.command.decision.feedback?.includes('AICO006_CANARY_')) {",
      '      await context.runner.query(',
      '        `INSERT INTO adapter_effect_ledger',
      '          (id,company_id,run_id,effect_kind,effect_key)',
      "         VALUES ($1,$2,$3,'EXTERNAL',$4)`,",
      '        [',
      '          newId(),',
      '          context.authority.companyId,',
      '          state.run_id,',
      '          request.command.decision.feedback,',
      '        ],',
      '      );',
      '    }',
    ),
  },
];
